spring.application.name=ecommerce_management

# MySQL
spring.datasource.url=${ECOMMERCE_DB_URL}
spring.datasource.username=${ECOMMERCE_DB_USERNAME}
spring.datasource.password=${ECOMMERCE_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Redis
spring.data.redis.host=${ECOMMERCE_REDIS_HOST}
spring.data.redis.port=${ECOMMERCE_REDIS_PORT}

# RabbitMQ
spring.rabbitmq.host=${ECOMMERCE_RABBITMQ_HOST}
spring.rabbitmq.port=${ECOMMERCE_RABBITMQ_PORT}
spring.rabbitmq.username=${ECOMMERCE_RABBITMQ_USER}
spring.rabbitmq.password=${ECOMMERCE_RABBITMQ_PASSWORD}

# Public API contract
spring.jackson.property-naming-strategy=SNAKE_CASE
logging.pattern.level=%5p [correlation_id=%X{correlation_id:-}]
